dataSource:
  hikari:
    driverClassName: "org.postgresql.Driver"
#    jdbcUrl: "jdbc:postgresql://localhost:5432/sakujj_db"
    jdbcUrl: "jdbc:postgresql://postgres:5432/sakujj_db"
    username: "postgres"
    password: "postgres"
    maximumPoolSize: 5
  executeOnStartUp:
    - "database-init/ddl.sql"
    - "database-init/dml.sql"
dao:
  cache:
    type: "LFU"
    capacity: 100