dataSource:
  driverClassName: "org.postgresql.Driver"
  jdbcUrl: "jdbc:postgresql://localhost:5432/sakujj_db"
  username: "postgres"
  password: "postgres"
  maximumPoolSize: 5
dao:
  cache:
    type: "LRU"
    capacity: 100